version: "3"

services:  
  mifos-app-server:
    build:
        context: ./mifos
        dockerfile: Dockerfile
    container_name: mifos-app-server
    restart: always
    expose:
      - "8443"
    networks:
      - mifos-network
    depends_on:
      mifos-db-server:
        condition: service_healthy
#     mifos-sms-server:
#       condition: service_healthy
    healthcheck:
      test: curl -kfsS https://127.0.0.1:8443 | grep 'Tomcat' | wc -l 
      interval: 5s
      retries: 20

  mifos-db-server:
    build:
        context: ./mysql
        dockerfile: Dockerfile
    container_name: mifos-db-server
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    healthcheck:
      test:  mysqladmin --user=root --password=mysql ping -h localhost
      interval: 5s
      retries: 20
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - mifos-network

#Nginx Service
  mifos_nginx_webserver:
    image: nginx:alpine
    container_name: mifos_nginx_webserver
    restart: unless-stopped
    tty: true
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=${HOST_URL}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${HOST_URL}
      - LETSENCRYPT_EMAIL=${MAIL_ENCRYPTION}
    volumes:
      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mifos-network
#  mifos-sms-server:
#    build:
#        context: ./activemq
#        dockerfile: Dockerfile
#    container_name: mifos-sms-server
#    restart: always
#    environment:
#      ACTIVEMQ_CONFIG_MINMEMORY: 512
#      ACTIVEMQ_CONFIG_MAXMEMORY: 1024
#    healthcheck:
#      test:  curl -u admin:admin -s http://localhost:8161/admin
#      interval: 5s
#      retries: 20  
#    networks:
#      - mifos-network

#Docker Networks
networks:
  mifos-network:
    external:
        name: nginx-proxy

#Volumes
volumes:
  dbdata:
    driver: local
